# Lan welcome message content
lan-message: "This server has Squaremap running, available <green><click:open_url:'http://192.168.1.237:8080/'><hover:show_text:'http://192.168.1.237:8080/'>[click]</hover></click><reset>."