name: LanJoinMessage
version: '${version}'
main: io.github.artificial720.lanjoinmessage.LanJoinMessage
api-version: '${minecraft_version}'
load: STARTUP
author: '${author}'
description: '${description}'